### ISSUE TITLE
fritzing part

### ISSUE THREAD

**Issue by ziporah** [sparkfun/Mega_Pro#2]
Is it possible to create a fritzing part for this component ?
I'm particulary interested in having the ISP available for the shield.
I know there are plenty of atmega's in fritzing, but I can't seem to find one with the spi available.

**Comment by ToniCorinne** [comment]
Hi @ziporah - I opened up a request to get this board generated for you. Once it's ready, it will appear in our [Fritzing Parts](https://github.com/sparkfun/Fritzing_Parts) repo, so I'd recommend keeping an eye on that. 

Thanks!
