### ISSUE TITLE
Bootloader?

### ISSUE THREAD

**Issue by fakedrake** [sparkfun/Mega_Pro#3]
Which bootloader does this board use and with what flags is it compiled? I am interested in the source code of the hex file `MegaPro3.3V-8MHz-57600.hex` found in the arduino ide.

**Comment by ToniCorinne** [comment]
It is a custom bootloader for the Mega boards.  You can see the pin definitions that are used for this in our board definitions repo [here](https://github.com/sparkfun/Arduino_Boards/blob/master/sparkfun/avr/variants/mega2560pro/pins_arduino.h). 

You can also find the specific flags for the Mega boards starting on line 229 of the [boards.txt](https://github.com/sparkfun/Arduino_Boards/blob/master/sparkfun/avr/boards.txt) file.
